version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://todo:todo@db/todo
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
